### ISSUE TITLE
[chore] Create Milestones

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-mobilizing-groups#7]
Create the following milestones, once issue #6 is closed

**Semester Milestones:**
1. Final version of the event organization control center Mockup (due to the end of the semester) 
2. Final draft of the API operations for the event organization control center (due to the end of the semester) 
3. **[Optional]** Final version of the working groups management API (due to the end of the semester)
4. **[Optional]** Initial prototype implementation of API with [playframework](https://www.playframework.com/)

**Current Week Milestones:**
1. Event's Mockup version 2
2. Initial list of operations version 1

**Comment by cdparra** [comment]
**Quick observation:** the milestones listed in the description of the issue are the **semester milestones**, useful only to remind us . To have a better focus, however, each week we will define weekly milestones. Description has been updated to reflect this.

**Comment by frschmidt** [comment]
What exactly is considered the end of the semester? Because I want to set the deadline.
